### PR TITLE
fix: resolve route binding query

### PR DESCRIPTION
**Pull request by bensherred**
This fixes an issue with the `resolveRouteBindingQuery` and using hashids.

Some packages/tools such as Filament PHP use this method under the hood for resolving models.

### CODE REVIEW

**Comment by bensherred** [comment]
Hey @deligoez, I was wondering if it would be possible to get a review on this one when you have 5 minutes.

**Comment by deligoez** [comment]
Hello @bensherred,

I came across your submitted PRs and appreciate your contributions.

Please note that I am currently on vacation and will be able to review your PRs in a few days. Thanks for your patience!

**Comment by bensherred** [comment]
Thanks @deligoez, enjoy your vacation! 🏝️

**Comment by bensherred** [comment]
Hey @deligoez, just wondering if you had been able to take a look at this PR yet?

**Comment by bensherred** [comment]
@deligoez, sorry to pester but just wondering if there were any updates on these PR's?

**Comment by deligoez** [comment]
@bensherred Thank you very much!

**Pull request merged**
